In [1]:
from src.hmm import MultiCatEmissionHMM
import numpy as np

In [2]:
B_1 = np.array([
    [0.5, 0.2, 0.3],
    [0.0, 0.2, 0.8]
])

B_2 = np.array([
    [0.6, 0.4],
    [0.1, 0.9]
])

Bs = np.concatenate([B_1, B_2], axis=1)
Bs

array([[0.5, 0.2, 0.3, 0.6, 0.4],
       [0. , 0.2, 0.8, 0.1, 0.9]])

In [3]:
hmm = MultiCatEmissionHMM(
    init_A = np.array([
        [0.7, 0.3],
        [0.2, 0.8]
    ]),

    init_Bs = Bs,

    init_pi = np.array(
        [0.5, 0.5]
    ),

    num_emission_symbols = np.array(
        [3, 2]
    )
)

In [4]:
observations = [np.array([[0, 1], [1, 0], [1, 1], [1, 0]]), np.array([[0, 1], [1, 0], [0, 0], [1, 1]])]

In [5]:
hmm.viterbi(Ys=observations[0])

[0, 0, 0, 0]

In [6]:
hmm.fit(observations)

100%|██████████| 10/10 [00:00<00:00, 502.28it/s]

[array([0.00095016, 0.00077482]), array([5.46420308e-04, 7.49552388e-05])]
0.0001909000000000001 0.001173180117405637
[array([0.00660809, 0.00251556]), array([0.0037471 , 0.00025999])]
0.001173180117405637 0.006565371529120848
[array([0.00740897, 0.00203348]), array([0.00429412, 0.00022589])]
0.006565371529120848 0.006981223512610962
[array([0.00751843, 0.00194441]), array([0.0043888 , 0.00021175])]
0.006981223512610962 0.007031697461991178
[array([0.00756192, 0.001999  ]), array([0.00443163, 0.00020848])]
0.007031697461991178 0.0071005170675653515
[array([0.00760708, 0.00204758]), array([0.00446968, 0.00020747])]
0.0071005170675653515 0.007165904276899582
[array([0.00764688, 0.00206776]), array([0.00449985, 0.00020648])]
0.007165904276899582 0.007210486891524919
[array([0.00768038, 0.00207076]), array([0.00452336, 0.00020542])]
0.007210486891524919 0.00723995292953873
[array([0.00770878, 0.00206586]), array([0.00454227, 0.00020438])]
0.00723995292953873 0.007260644403385384
[array([0.

In [7]:
hmm.Bs

array([[0.36182671, 0.63817329, 0.        , 0.50972553, 0.49027447],
       [0.        , 1.        , 0.        , 0.45557048, 0.54442952]])

In [8]:
import numpy as np
from scipy.special import kl_div, softmax

gt = np.random.random(size=(20,)).astype(np.float64)
gt /= gt.sum()
gt.sum() 

1.0

In [9]:
params = np.random.random(size=(20,)).astype(np.float64)

def kl_divergence(p, q):
    return np.sum(np.where(p != 0, p * np.log(p / q), 0))

func = lambda x: kl_divergence(gt, softmax(x))


In [10]:
func(params)

0.10188363730712842

In [11]:
from scipy.optimize import minimize

optim_results = minimize(func, x0=params)

In [12]:
func(optim_results.x)

3.465182447850946e-09

In [13]:
params, softmax(optim_results.x), gt

(array([0.28494411, 0.52413616, 0.6136314 , 0.75998437, 0.83289812,
        0.65194011, 0.24980404, 0.92921042, 0.10042986, 0.85224165,
        0.66790417, 0.21285433, 0.48757106, 0.35100469, 0.83659623,
        0.93541758, 0.46782697, 0.35480091, 0.12212223, 0.04047057]),
 array([0.03707182, 0.0757822 , 0.03949315, 0.05997625, 0.0580253 ,
        0.06545243, 0.09821426, 0.09454248, 0.05059853, 0.06686423,
        0.03766553, 0.00584065, 0.02257706, 0.03940797, 0.07583694,
        0.05030256, 0.03530309, 0.04471975, 0.03535208, 0.00697371]),
 array([0.0370685 , 0.07578682, 0.03948871, 0.05997472, 0.05802459,
        0.06545286, 0.09821229, 0.09455052, 0.05060047, 0.0668634 ,
        0.03766428, 0.00583842, 0.02257465, 0.03940502, 0.07583771,
        0.0503082 , 0.03530923, 0.04472221, 0.03534425, 0.00697313]))