In [1]:
from src.hmm import MultiCatEmissionHMM
import numpy as np

In [2]:
B_1 = np.array([
    [0.5, 0.2, 0.3],
    [0.0, 0.2, 0.8]
])

B_2 = np.array([
    [0.6, 0.4],
    [0.1, 0.9]
])

Bs = np.concatenate([B_1, B_2], axis=1)
Bs

array([[0.5, 0.2, 0.3, 0.6, 0.4],
       [0. , 0.2, 0.8, 0.1, 0.9]])

In [3]:
hmm = MultiCatEmissionHMM(
    init_A = np.array([
        [0.7, 0.3],
        [0.2, 0.8]
    ]),

    init_Bs = Bs,

    init_pi = np.array(
        [0.5, 0.5]
    ),

    num_emission_symbols = np.array(
        [3, 2]
    )
)

In [4]:
observations = [np.array([[0, 1], [1, 0], [1, 1], [1, 0]]), np.array([[0, 1], [1, 0], [0, 0], [1, 1]])]

In [5]:
hmm.viterbi(Ys=observations[0])

[0, 0, 0, 0]

In [6]:
hmm.fit(observations)

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:00<00:00, 591.20it/s]

0.010723467210298444
0.011354933170176967
0.011441826230042711
0.01163320937026847
0.011708823837334459
0.011686816280644437
0.011627349669026642
0.011559737042571603
0.011494693138477553
0.0114356177542874
0.011383139729459528
0.011336889486652523
0.011296197196322834
0.011260358944433203
0.011228729144451598
0.01120074473265451
0.011175924057089861
0.011153857612211314
0.011134197224953863
0.011116646029661939
0.011100949885520114
0.011086890262284908
0.011074278415787023
0.011062950633587802
0.01105276434764726
0.011043594943223588
0.011035333126050047
0.01102788273821097
0.011021158936176726
0.011015086662656206
0.01100959935814072
0.011004637869081263
0.011000149518270469
0.010996087309749537
0.010992409245864943
0.01098907773828926
0.010986059098147028
0.01098332309304309
0.010980842560921758
0.010978593072404973
0.010976552634651249
0.010974701430912214
0.010973021590892935
0.010971496987785318
0.010970113058474581
0.010968856643941115
0.010967715847315153
0.010966679907405208
0

In [7]:
hmm.Bs

array([[0.38660203, 0.61339797, 0.        , 0.49834764, 0.50165236],
       [0.        , 1.        , 0.        , 0.31673772, 0.68326228]])

In [8]:
import numpy as np
from scipy.special import kl_div, softmax

gt = np.random.random(size=(20,)).astype(np.float64)
gt /= gt.sum()
gt.sum() 

1.0

In [9]:
params = np.random.random(size=(20,)).astype(np.float64)

def kl_divergence(p, q):
    return np.sum(np.where(p != 0, p * np.log(p / q), 0))

func = lambda x: kl_divergence(gt, softmax(x))


In [10]:
func(params)

0.26059264187414277

In [11]:
from scipy.optimize import minimize

optim_results = minimize(func, x0=params)

In [12]:
func(optim_results.x)

4.4398274859606555e-09

In [13]:
params, softmax(optim_results.x), gt

(array([0.99134597, 0.56646038, 0.56132677, 0.70195435, 0.25414078,
        0.44882285, 0.72489184, 0.74483942, 0.88110597, 0.18125203,
        0.65394145, 0.05632188, 0.56124451, 0.42099012, 0.21603122,
        0.39622249, 0.41064124, 0.76806691, 0.92603578, 0.44920796]),
 array([0.04571894, 0.0347056 , 0.00830453, 0.05140216, 0.01785568,
        0.04016334, 0.07777983, 0.01169725, 0.05469597, 0.07962045,
        0.0273793 , 0.06059023, 0.09857637, 0.06496407, 0.0624321 ,
        0.09012865, 0.00643165, 0.01202882, 0.048256  , 0.10726907]),
 array([0.04571434, 0.03471136, 0.00830661, 0.05140522, 0.01785976,
        0.04015975, 0.07778544, 0.01169576, 0.05469984, 0.07961247,
        0.02737552, 0.06058253, 0.09856672, 0.0649722 , 0.06243103,
        0.09013092, 0.00643098, 0.0120291 , 0.04825672, 0.10727371]))