In [1]:
from src.hmm import MultiCatEmissionHMM
import numpy as np

In [2]:
B_1 = np.array([
    [0.5, 0.2, 0.3],
    [0.0, 0.2, 0.8]
])

B_2 = np.array([
    [0.6, 0.4],
    [0.1, 0.9]
])

Bs = np.concatenate([B_1, B_2], axis=1)
Bs

array([[0.5, 0.2, 0.3, 0.6, 0.4],
       [0. , 0.2, 0.8, 0.1, 0.9]])

In [3]:
hmm = MultiCatEmissionHMM(
    init_A = np.array([
        [0.7, 0.3],
        [0.2, 0.8]
    ]),

    init_Bs = Bs,

    init_pi = np.array(
        [0.5, 0.5]
    ),

    num_emission_symbols = np.array(
        [3, 2]
    )
)

In [4]:
observations = np.array([[0, 1], [1, 0], [1, 1], [1, 0]]) # (D, not B), (C, B), (C, not B), (W, B)

In [5]:
hmm.predict(Ys=observations)

[array([1., 0.]),
 array([0.93333333, 0.06666667]),
 array([0.66666667, 0.33333333]),
 array([0.82222222, 0.17777778])]

In [6]:
hmm.viterbi_mv(Ys=observations)

[0, 0, 0, 0]